spring.application.name: springboot-project-backend

spring:
    amqp:
      deserialization:
        trust:
          all: true

    mail:
      host: smtp.163.com
      username: 15228204975@163.com
      password: 
    rabbitmq:
      addresses: localhost
      username: guest
      password: guest
      virtual-host: /
      port: 5672

    security:
      filter:
        order: -100
      jwt:
        key: abcdefg
        expire: 1
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 
      url: jdbc:mysql://localhost:3306/spring_project
